### ISSUE TITLE
Using var.ci ?

### ISSUE THREAD

**Issue by Marsup** [hapijs/contrib#115]
Hey crowd,

I was wondering if people were OK if I allowed https://var.ci/ to act on my repos issues.
Github permission are done in such a way that I think I'd be allowing their bot entire access to our organization.

It's just to run some simple rules when issues or PRs are created, like, I don't know, auto-close or reply to issues when people entirely disregard the issue template...

**Comment by sirgallifrey** [comment]
> It's just to run some simple rules when issues or PRs are created, like, I don't know, auto-close or reply to issues when people entirely disregard the issue template...

I think a bot for that would be great.

Just don't know what to think about it having access to the entire org :P

**Comment by devinivy** [comment]
I'm not familiar with exactly what var.ci does.  But I am somewhat sensitive to bots handling issues– I've seen it frustrate community members (in other communities) many times.  I guess I would just suggest we proceed with caution and pinpoint exactly what features the bot has to provide the maintainer (and by extension, the community) value.  I'm not personally opposed to that service having access to the organization in order to help you with Joi, but I wouldn't support it running against all the hapi repos until it has proven itself to be a positive/neutral experience for the community and helps maintainers.

**Comment by AdriVanHoudt** [comment]
Seems useful but the messaging and rules should be handled with care like @devinivy said, but stuff like auto closing after 2 weeks of no reply seems useful
