### ISSUE TITLE
Browser support

### ISSUE THREAD

**Issue by hueniverse** [hapijs/contrib#32]
This is coming up over and over again. See https://github.com/hapijs/boom/pull/58 for some context. Basically, someone wants to use a hapi.js module in the browser but whatever they use to make that work is grabbing a pile of shit with it (like the entire http module, or other dependencies with large footprint).

Whenever that happens we get into long arguments about why we do or do not care about this use case and if the proposed changes are worth the hassle.

My position on this is simple - hapi.js is a server-side ecosystem. Period. If we can accommodate client side usage without extra effort, great. If we can't, we should at a minimum require proof that there is an equally big market for the module on the client side before even engaging in the effort. It seems to me that most of these issues could be resolved by improvements to browerify and other such solutions than constantly requesting changed to the modules.

In addition, once we agree to make such changes we are basically committing the module to browser compatibility which is a significant limitation on it's growth.

The most I have agreed in the past was to add some fields to the package.json file to help client-side tools handle the module. But I have rejected requests to make code changes to allow the same code to work on both platforms.

I think we should have a community policy on this to guide maintainers on how to respond (while allowing them to decide on the final outcome on a case-by-case basis).

**Comment by devinivy** [comment]
My gut reaction is to oppose supporting browser usage.  What are folk trying to achieve?  I could see the router and other components coming in handy on the front-end.  Maybe call could use a meaningful wrapper for in-browser use.  I could also see the barebones request lifecycle being useful on the front-end, but it's likely that most of the steps/events are too HTTP-specific.  I imagine it's mere accident if hapi can easily cater to client-side usage.

**Comment by gergoerdosi** [comment]
> In addition, once we agree to make such changes we are basically committing the module to browser compatibility which is a significant limitation on it's growth.

I think this is an important point. Modules under the hapijs organization have high quality, and by this I mostly mean the 100% code coverage. If we decide to support a module in browsers, then I think we should have the same quality requirements. Code should be tested on Chrome, Safari, Firefox, IE, etc. Which probably requires a lot of changes to the test suite.

**Comment by abritinthebay** [comment]
>  I could see the router and other components coming in handy on the front-end. Maybe call could use a meaningful wrapper for in-browser use. I could also see the barebones request lifecycle being useful on the front-end

This is *exactly* the situation I described in my original issue that started this. I wanted a Hapi compatible router (to allow route reuse with minimal extra configuration) and Call + Boom + Hoek basically added about 800k of (unminified) code which is... insane for a router on the browser.

Obviously on Node it's not an issue but on the browser? It totally is.

Hapi the *server* doesn't need to be browser friendly, of course. That would be a bit silly. But Hapi the *ecosystem*? It currently is actively *unfriendly*.

Obviously not all modules would need to be friendly - that could be per-module. I don't think you need to make that a blanket hapi-wide choice. Yes, it would require a little more testing, but with Browser compatibility things like Browserify and es5-shim should get you the whole way with relative ease at a minor file-size penalty at *worst* (and running your tests in multiple browsers and versions is trivial with a decent CI service)

Long term it's about: Do you want Hapi to be useful to isomorphic javascript applications or not? If not, fine, I guess. It would be a shame and I think a waste of a great potential that Hapi has (given it's configuration-based philosophy it's a natural fit) but people would work around it eventually (or move on to something that was friendlier) but if yes... then this is just what has to happen long term.

**Comment by devinivy** [comment]
For the sake of saving time, perhaps fork call and adapt it to work on both browser and client.  Even if that's the case, it sounds like we need to decide here what sort of policy the community should have around accepting these changes, what sort of testing is necessary, etc.

What I'm getting at: barring the hapi community outright denying client-side support, maybe it's time for someone who's interested to try to adapt a module and issue a PR, just to see how hard this problem really is and what sorts of unforeseen problems or simplifications will arise.

**Comment by abritinthebay** [comment]
Well... that already got rejected (see... Boom). But yes, I agree.

**Comment by ulrikaugustsson** [comment]
I think we need some isomorphic story for hapi, or maybe we could try to make it easier for the community to create and share client side modules that is compatible?
I think this is important, or at least interesting as hapi isn't only used for APIs.

**Comment by nlf** [comment]
I tend to measure this in level of effort required.. If I have to refactor the entire module, it's likely not gonna happen. If it's a matter of changing a handful of lines of code, then I'm fine with it.

Obviously every module is going to be different, some will likely work in the browser with no significant changes while others may require considerably more work. Whether or not to support use in the browser should definitely be addressed case by case.

I think a good starting point is requesting that the people that want this functionality open an issue explaining their use case so it can be determined if a different module already fills their need. If one does not exist, then it can be up to the module's maintainer to determine the level of effort required and whether they're willing to support it. In some cases it may be simpler to create a fork of the module with pared down functionality that is specifically for the browser.

**Comment by abritinthebay** [comment]
I can tell you *exactly* what would be needed for Hoek, Call, and Boom. Because I've done it - I gave up on getting it done upstream and just copied the code into my module and made the edits myself.

**Hoek** - would require pulling out the crypto lib part into a separate include. That's about it. Some very minor Buffer shimming as well (for the Buffer.isBuffer checks) which can be done with an if (process.browser) check.

**Boom** - basically my PR above; pull the http STATUS_CODES out of the http module (or make a simple build script that can do it automatically) and add that browser override to the package.json (or make it a core lib change, either works). 

**Call** - pretty much *nothing* once you've done the two above. Call doesn't actually do everything that Hapi does API wise so I had to shim how Hapi works with Call to get Hapi -> Browser API compatibility but that's a different point. 

Those changes (which took me like... an hour tops, ignoring the Hapi compatibility layer over Call) save **approximately 800k in the browser** when the code is unminified and ungziped. With those it does down to like... 160k but still... that's a lot of code, bandwidth, and *loading speed* saved with very little work.

**Comment by abritinthebay** [comment]
> In some cases it may be simpler to create a fork of the module with pared down functionality that is specifically for the browser.

In some, sure, but in Boom and Hoek and Call that is trivially demonstrated that isn't the case. I think for *some* modules it makes sense to not even have browser support (like the core Hapi server) because it would make no sense.

But generally speaking most things can be made browser friendly with no real effort.

**Comment by nlf** [comment]
I mentioned in the issue for hoek that I was open to a PR, but one was never submitted. Why don't you go ahead and submit one and link it here so everyone can see what it looks like to support the browser in this way? That will give us more detail for discussion

**Comment by abritinthebay** [comment]
Sure! Will do (though it'll likely have to wait a little as I'm in the middle of work deadlines today). After the quite negative reaction to my Boom PR by everyone other that @arb  I sort of figured that it wouldn't get accepted anyhow so didn't bother.

Will get on it.

**Comment by csrl** [comment]
Personally, I like that Hapi has its own ecosystem of modules focused on the server.  It'd be unfortunate if any changes affect the efficiency and simplicity of the modules just so that they work in the browser.

That said, in the example of Hoek dependency on Crypto, it does seem that the single use of Crypto could be avoided.   I'd suggest submitting pull requests with the motivation to reduce dependency and code complexity.  I understand that is a driving design motivator behind hapi modules anyway.

**Comment by abritinthebay** [comment]
I don't think the modules simplicity should be compromised for the browser *at all*. In fact I think it helps to make the modules simpler, smaller, and more, well... *modular* because then, ideally, all you need to do is simple `package.json` stuff to make the browser stuff work.

Obviously when a module is purely server-side then there is no need but it's surprising how just small differences can add up (like I said - 800k of code in my case... yeesh)

(Need to polish up that modified Hoek code at get a PR ready... *sigh*)

**Comment by epiloque** [comment]
Hello,

Just finished the Boom helper methods [port](https://github.com/epiloque/error-objects) for the browser, with minimal changes thanks to @hueniverse and @hapijs community. Few highlights from the process:

* Mocha & Chai replaced Lab for tests
* Browserify, Babel bundles & transforms the code to ECMAScript 5 
* Karma runs the tests in BrowserStack & PhantomJS
* The bundle normal size is 4.5K (not-minified, not-gzipped)
* Tested on IE 9+, Chrome 16+, FireFox 5+, Safari 6+, Opera 12+. See travis-ci [build-logs](https://travis-ci.org/epiloque/error-objects).

I'm porting [Call](https://github.com/epiloque/error-objects) next, so feedback & guidance is much appreciated.

I agree with @hueniverse that separation and forks are the way to go, browser libraries have a big tooling & management overhead.

Thank you!

**Comment by arb** [comment]
Is all this just to avoid using babel on some node_modules? I feel like if you want to use these modules on front end, you'll have a better experience dealing with the source code directly, rather than working with transpiled code. 

Secondly, take Joi for example, all you need to do in your webpack config is set a few node modules to empty, run it through babel, and now you've got Joi on the client. That's all it takes. It put's the environment management with you, the module consumer. Rather than trying to have the author's guess what context you're going to use it in.

It would be different if there was a single build tool people use; but there isn't. webpack, browserify, roll-up, and there will probably be a new one by the time you're finished reading this sentence. As an org, we've stopped supporting older versions of Node and don't supply transpiled/compatible versions for legacy versions of Node.

That being said, if there are SMALL code changes that would make using on the client easier, I would support that. In boom for example, I removed the `http` module and just created all the status codes myself. @abritinthebay and @epiloque FYI - https://github.com/hapijs/boom/commit/f51f2eeba5fae1b79f79c14b2c42d110f0433b2c

**Comment by epiloque** [comment]
@arb I agree with second point & I did not understand the first one. Also, I'm **not** trying to push for a merge.

I have a frequent use-case: route sharing between hapi and the browser. To my knowledge there are no browser routing libraries with compatible logic & route syntax. Call depends on parts of Hoek & Boom and I'm porting that relevant parts and ensuring browser support. Apart from that, I haven't encountered another use case.

I'm not a hapijs contributor, so apologies for the overreach in thoughts. Hoek, Joi, Boom &c. are not universal libraries and they should not be. There are hundreds of utility/validation/error libraries meticulously tailored for numerous browser quirks. There is no good reason for Hoek, Joi or Boom to work around browser problems. Thanks to all of you Hapi is exceptionally good at what it does.

**Comment by epiloque** [comment]
Finished the Call [port](https://github.com/epiloque/evoke). Tests pass for IE 9+, Chrome 16+, FireFox 5+, Safari 6+, Opera 12+. See travis-ci [build-logs](https://travis-ci.org/epiloque/evoke). The bundle normal size is 20k (not-minified, not-gzipped).

**Comment by abritinthebay** [comment]
the http module is one of two major issues I had with browser support. The other was that it imported the *crypto* module for, I think, one function.

Obviously the crypto module is massive.

**Comment by abritinthebay** [comment]
Currently I have an internal implementation that just strips that stuff, but it's going to go away when I make my client side routing respond to state, not routes, so... *shrugs* that's one work around.

Loading less modules in general is always good though, even on the server side.
