### ISSUE TITLE
Town Hall Meeting/Fireside Chats

### ISSUE THREAD

**Issue by arb** [hapijs/contrib#34]
I was wondering if we wanted to take a page from the IO folks and have like public Google Hangouts every so often to discuss things of import in the hapijs universe. It would be attended by a some lead maintainers and anyone in the community could jump on to submit questions. I think it could be a fun way to interact with the community in a more personal way than text on GitHub issues.

Is this something that anyone would be interested in?

**Comment by AdriVanHoudt** [comment]
I like the idea!

**Comment by cjihrig** [comment]
A few questions based on my experience with io.js/node.

- How frequent of a meeting schedule are you proposing?
- Who specifically is on the list of invitees? You said anyone can jump on, but if you're trying to accommodate specific people, you'll have to take things like time zones into account.
- Will there be smores?
- What meeting software would you use? Google hangout would probably be preferred, but maxes out pretty quick. io.js/node recently moved to Uberconference because of head count.

**Comment by arb** [comment]
- I would say monthly at the most frequent
- I'm not sure about invitees... maybe everyone who is in the "Core project maintainers" group and they would do the bulk of the speaking (agenda items, group discussion, etc). The broader community members would be able to submit written questions and we would open it up for speaking as a whole at the end of meeting? The discussion should *NOT* devolve into technical questions like "how do I deploy a hapi server to production". I would like it to stay more about the community, direction, and open source opportunities. I'm just spitballing ideas here; what has worked or not worked for node/io?
- Yes
- I'm open to suggestions... something that is free. Google Hangouts caps out at 8 which isn't ideal so a different platform would be preferred.

**Comment by jaw187** [comment]
Mmmmmm smores...

Capping at 8 participants might be a good thing.  Questions could be
fielded via Github ahead of time or via twitter in real time.

**Comment by cjihrig** [comment]
@arb my experience with the node/io calls has been different from what you're describing since they have been almost completely technically focused. Either way, it's really important to have an agenda for the call, which we've managed using a label on Github issues. We've also solicited questions from the community in real time over IRC, although Gitter would be viable too. I think the same model could work for hapi if there is enough interest.

**Comment by arb** [comment]
@hapijs/core-project-maintainers sorry for the spam, but is this something you are interested in moving forward with? If not I'll just close this and move on.

**Comment by Marsup** [comment]
As already discussed with you, I'm not that motivated by that.

**Comment by hueniverse** [comment]
I would probably make sense to start with asking people if they have topics/questions and see if there is an interest in doing this.

**Comment by nlf** [comment]
I agree, I haven't really seen many things come up that would warrant that much discussion. I'm not opposed to the idea at all, I'm just not sure if the interest is really there in general.
