### ISSUE TITLE
Why was shrinkwrap.json added to hapi, but not in other modules?

### ISSUE THREAD

**Issue by dominykas** [hapijs/contrib#64]
I understand the rationale for shrinkwrap.json overall (and #26 sheds some light too) - but why is it only added on the "master" project and not in dependencies?

**Comment by hueniverse** [comment]
Because hapi.js is about hapi, the core framework. We want to give people the comfort and security of knowing that if they install the blessed version using the shrinkwrap, they will get a combination that was fully reviewed and tested. However, they can call `npm update` and get the latest of all the dependencies all the way down.

**Comment by dominykas** [comment]
But it's not because of bugs or undefined/unexpected behaviors that boom, wreck et al don't have a shrinkwrap?

**Comment by hueniverse** [comment]
They don't need it.

**Comment by dominykas** [comment]
OK, thanks :)
