### ISSUE TITLE
Change release notes format

### ISSUE THREAD

**Issue by Marsup** [hapijs/contrib#92]
Reading https://github.com/hapijs/discuss/issues/349 I was wondering, should we change our way to publish release notes to allow contribution ?

If someone wants to improve upon it, it's simply impossible other than having a debate about it, probably in the release notes themselves as it seems more natural.

Now that we're excluding all non-essentials from our npm packages, what do you think of having it directly in the repo ?

**Comment by AdriVanHoudt** [comment]
You can comment on it no?

**Comment by Marsup** [comment]
That's exactly what I'm saying in this issue. Sure you can comment on it, but are you really going to submit modifications to it in the issue itself ? Not such a good and easy process...

**Comment by AdriVanHoudt** [comment]
That is true. So instead of an issue make a changelog.md?
We need to make sure hapijs.com/updates will work with this, since it now links to the issue with release notes.

**Comment by Marsup** [comment]
Or individual markdown files.

**Comment by devinivy** [comment]
I like that this makes them more portable, and that they can be featured on the site more easily.  I don't think we _need_ to optimize for the ability for folks to contribute to them since any of us can update the guide based upon feedback/comments.  We would give-up the ability to have a conversation about the release via comments– for that reason, if this goes through I'd suggest that we also make an issue (as we typically do) with a hyperlink to the release notes.

**Comment by thebergamo** [comment]
In my last company, the changelog.md is a gist file served on the site, and in gists you can comment directly in a file instead of opening an issue. Maybe more centralized?

**Comment by Marsup** [comment]
@devinivy fair point, that doesn't prevent anyone from opening new issues about it or comment on the commit, but sure you have to have a little bit of github knowledge.

@thebergamo gists are really not easy to use in collaboration, plus you get no notification when there are comments, won't work.

If no one thinks the community would like to be involved in improving release notes I'm happy with the status quo as well.
