### ISSUE TITLE
Additional tags in hapijs/discuss

### ISSUE THREAD

**Issue by devinivy** [hapijs/contrib#98]
Given that https://github.com/hapijs/discuss cross-cuts many hapi-related topics, I wanted to put forth the idea of adding additional labels to that repo to coarsely reflect those topics.  The goal of this issue is to decide whether that's worthwhile and if so, to land on some initial labels.  I think ideally the labels would be decided on here rather than created ad-hoc on the repo, for tidiness's sake.  Some examples, `cors`, `caching`, `plugins`, `realms`, `request-lifecycle`, `logging`, `auth`.

As someone who answers many questions in hapijs/discuss, I support this idea because good, in-depth discussions/clarifications take place there that go beyond information you'd find in documentation and tutorials, yet the knowledge poured into hapijs/discuss is currently far more useful than it is searchable.

**Comment by Marsup** [comment]
I've always felt comfortable with a complete lack of labels in this repo since those are mainly discussions/questions. What do you expect this would achieve having not only additional labels but labels at all ?

**Comment by devinivy** [comment]
I would hope for it to help folks find issues that a contributor has labeled because it contains useful and accurate information that goes beyond direct interpretation of the API docs.  I learned a lot about hapi by reading through past discussions in hapijs/discuss, or following them as they occurred.  It would have been nicer/easier to browse areas of personal interest if they were also labeled.  Maybe I'm the only person who's into learning that way, though– I don't know!

**Comment by AdriVanHoudt** [comment]
@devinivy do you have an example of issue that would benefit from it?

**Comment by nlf** [comment]
i, too, have been comfortable with the lack of labels since for the most part the issue titles have been fairly descriptive, and when i have a problem i tend to not bother looking at labels and go straight to the search.

i could potentially see some benefit in having labels in that it could help encourage people to answer questions, as in "oh this person is asking about cors, i know something about that." but odds are if you're in the issues to answer questions you're probably going to click on them whether they're labeled or not (i would think).

the "problem" with labels is making sure they're accurate. the person posting the question won't necessarily know if their question relates to a plugin, cors, or the request lifecycle, so they may take a guess. if they're wrong now that label is misleading which is causing more harm than good, and creating work for someone who has to go in and change it.

i kinda feel like it's more work than it's worth, but i'm certainly open to differing opinions. if no one else has anything to say i'll probably close this issue in a couple days.

**Comment by devinivy** [comment]
It doesn't seem like a popular idea– I have no qualms closing it out!  It's only useful if folks actually use them :)

@AdriVanHoudt sorry I missed your comment!  Here are three example labels for some issues I found in the first page of open issues.
`auth` - https://github.com/hapijs/discuss/issues/422
`caching` - https://github.com/hapijs/discuss/issues/431
`testing` - https://github.com/hapijs/discuss/issues/424
